version: '2.2'
services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: image-service
      POSTGRES_USER: image-service
      POSTGRES_PASSWORD: image-service
    healthcheck:
      test: [ 'CMD', 'pg_isready', "-q", "-d", "image-service", "-U", "image-service" ]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s

  postgres-db-test:
    image: postgres:latest
    container_name: postgres-db_test
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: image-service-test
      POSTGRES_USER: image-service
      POSTGRES_PASSWORD: image-service
    healthcheck:
      test: [ 'CMD', 'pg_isready', "-q", "-d", "image-service-test", "-U", "image-service" ]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 5s

